[mypy]
python_version = 3.13
files = src/webcam_mods/settings.py, src/webcam_mods/timing.py, src/webcam_mods/models.py, src/webcam_mods/mods/record_replay.py, src/webcam_mods/input/input.py, src/webcam_mods/input/video_dev.py, src/webcam_mods/session.py, src/webcam_mods/utils/config.py
follow_imports = silent
ignore_missing_imports = True
strict = True
warn_unused_configs = True
